"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

import django
from django.contrib.messages import constants as messages
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a .env file in BASE_DIR (if present) into the
# environment. In production the .env file lives on the server only and is
# never committed to git (see .gitignore).
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer DJANGO_SECRET_KEY from the environment; fall back to the legacy
# secret_key.txt file for backward compatibility with existing deployments.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    secret_key_file = BASE_DIR / 'secret_key.txt'
    if secret_key_file.exists():
        SECRET_KEY = secret_key_file.read_text().strip()
    else:
        raise RuntimeError(
            'DJANGO_SECRET_KEY is not set. Define it in your .env file '
            '(see .env.example).'
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Comma-separated list of allowed hosts, e.g.
# DJANGO_ALLOWED_HOSTS=zacoinfotech.com,www.zacoinfotech.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]
if DEBUG:
    # Local development: always allow the loopback addresses, even when .env
    # lists only the production domains.
    ALLOWED_HOSTS += [h for h in ('127.0.0.1', 'localhost', '[::1]') if h not in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home.apps.HomeConfig',
    'canada.apps.CanadaConfig',
    'services.apps.ServicesConfig',
    'blog.apps.BlogConfig',
    'django_summernote',
    'ckeditor',
    'usa',

  

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise: serve compressed, cache-busted static files directly from
# gunicorn without needing nginx/S3 for static assets.
# https://whitenoise.readthedocs.io/
#
# Django 4.2 replaced STATICFILES_STORAGE with STORAGES (and 5.1 dropped the
# old name), while requirement.txt currently pins 4.0.4 - so support both.
if django.VERSION >= (4, 2):
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'website.storage.ForgivingManifestStaticFilesStorage'},
    }
else:
    STATICFILES_STORAGE = 'website.storage.ForgivingManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# HTTPS / HSTS settings — enabled automatically once DEBUG is off and the
# site is served over HTTPS behind nginx (see DEPLOYMENT.md). Keep these
# off for local HTTP development.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # nginx terminates TLS and proxies to gunicorn over plain HTTP, setting
    # this header so Django knows the original request was HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_USE_TLS = True
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Gmail rewrites the From header to the authenticated account anyway, so use
# it directly when set; visitors' addresses go in Reply-To instead.
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@zacoinfotech.com'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Every enquiry (contact form, newsletter signup) is emailed to all of these.
# Override with LEAD_NOTIFICATION_EMAILS=a@x.com,b@y.com in .env.
LEAD_NOTIFICATION_EMAILS = [
    e.strip()
    for e in os.environ.get(
        'LEAD_NOTIFICATION_EMAILS',
        'info@zacoinfotech.com,abhiraj@zacocomputer.com',
    ).split(',')
    if e.strip()
]

# Contact details shown across the site (exposed to templates by
# home.context_processors.site_contact). Change the number here only.
CONTACT_PHONE_DISPLAY = '+91 97025 73082'
CONTACT_PHONE_TEL = '+919702573082'
CONTACT_WHATSAPP = '919702573082'

SUMMERNOTE_THEME = 'bs4'




